name: End-to-end Tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup project
      uses: ./.github/actions/setup
      
    - name: Install Playwright Browsers
      run: pnpm exec playwright install --with-deps
      
    - name: Run Playwright tests
      run: pnpm --filter @repo/site exec playwright test
      
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
