name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup project
        uses: ./.github/actions/setup
      
      - name: Build packages
        run: pnpm build
        
      - name: Upload style token artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: tokens-json
          path: |
            packages/style-tokens/dist/css/tokens.json
            packages/style-tokens/dist/css/variables.css

      - name: Run tests
        run: pnpm test
        
      - name: Check types
        run: pnpm check-types

      - name: Lint
        run: pnpm lint
        
      - name: Check formatting
        run: pnpm format --check
